eTUTOR/Models/common.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTUTOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common
    {
        public common()
        {
            this.submenus = new HashSet<submenu>();
        }
    
        public int common_id { get; set; }
        public string menu { get; set; }
        public string header { get; set; }
        public string footer { get; set; }
    
        public virtual ICollection<submenu> submenus { get; set; }
    }
}

eTUTOR/Controllers/TutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eTUTOR.Controllers
{
    public class TutorController : Controller
    {
        // GET: Tutor
        public ActionResult ListOfTutors()
        {
            return View();
        }
        public ActionResult ViewDetailTutor()
        {
            return View();
        }
        public ActionResult InfoOfTutor()
        {
            return View();
        }
        public ActionResult RegisterTutor()
        {
            return View();
        }
    }
}

eTUTOR/Views/Shared/Common/_Footer.cshtml
<footer id="footer" class="footer divider layer-overlay overlay-dark-9" data-bg-img="img/slider/bg2.jpg" style="background-image: url(&quot;img/slider/bg2.jpg&quot;);">
    <div class="container">
        <div class="row border-bottom">
            <div class="col-sm-6 col-md-3">
                <div class="widget dark">
                    <img class="mt-5 mb-20" alt="" src="~/Content/img/logo-white-footer.png">
                    <p>203, Envato Labs, Behind Alis Steet, Melbourne, Australia.</p>
                    <ul class="list-inline mt-5">
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-color-2 mr-5"></i> <a class="text-gray"
                                                                                   href="#">123-456-789</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-envelope-o text-theme-color-2 mr-5"></i>
                            <a class="text-gray" href="#">contact@yourdomain.com</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-globe text-theme-color-2 mr-5"></i> <a class="text-gray"
                                                                                   href="#">www.yourdomain.com</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="widget dark">
                    <h4 class="widget-title">Liên kết</h4>
                    <ul class="list angle-double-right list-border">
                        <li><a href="@Url.Action("about","Home")">Giới thiệu</a></li>
                        <li><a href="@Url.Action("listOfTutors","Tutor")">Danh sách gia sư</a></li>
                        <li><a href="@Url.Action("contact","Home")">Liên hệ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <div class="widget dark">
                            <h5 class="widget-title mb-10">Hãy gọi cho chúng tôi</h5>
                            <div class="text-gray">
                                +61 3 1234 5678 <br>
                                +12 3 1234 5678
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="widget dark">
                            <h5 class="widget-title mb-10">Liêc lạc với chúng tôi</h5>
                            <ul class="styled-icons icon-bordered icon-sm">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12">
                        <h5 class="widget-title mb-10">Theo dõi thông báo</h5>
                        <form id="mailchimp-subscription-form-footer" class="newsletter-form" novalidate="true">
                            <div class="input-group">
                                <input type="email" value="" name="EMAIL" placeholder="Email của bạn" class="form-control input-lg font-16"
                                       data-height="45px" id="mce-EMAIL-footer" style="height: 45px;">
                                <span class="input-group-btn">
                                    <button data-height="45px" class="btn bg-theme-color-2 text-white btn-xs m-0 font-14"
                                            type="submit" style="height: 45px;">
                                        Theo dõi
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom bg-black-333">
        <div class="container pt-20 pb-20">
            <div class="row">
                <div class="col-md-6">
                    <p class="font-11 text-black-777 m-0">Copyright ©2016 ThemeMascot. All Rights Reserved</p>
                </div>
                <div class="col-md-6 text-right">
                    <div class="widget no-border m-0">
                        <ul class="list-inline sm-text-center mt-5 font-12">
                            <li>
                                <a href="#">FAQ</a>
                            </li>
                            <li>|</li>
                            <li>
                                <a href="#">Help Desk</a>
                            </li>
                            <li>|</li>
                            <li>
                                <a href="#">Support</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

eTUTOR/Views/Shared/Common/_Header.cshtml
<header class="menu" once="menu">
    <nav class="navbar navbar-expand-md  navbar-dropdown align-items-center navbar-dark nav--dark">
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="#">
                        <img src="" alt="">
                    </a>
                </span>
                <span class="navbar-caption-wrap">
                    <a class="navbar-caption text-white display-5 " href="">
                        eTuiTor
                    </a>
                </span>
            </div>
        </div>
        <button class="navbar-toggler btn-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse shift" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right ml-auto">
                <li class="nav-item  active  p-2">
                    <a class="nav-link link text-white " href="@Url.Action("index","Home")">
                        Trang chủ
                    </a>
                </li>
                <li class="nav-item  p-2">
                    <a class="nav-link link text-white " href="@Url.Action("about","Home")">
                        Giới thiệu
                    </a>
                </li>
                <li class="nav-item dropdown  p-2">
                    <a class="nav-link link  text-white " href="@Url.Action("listOfTutors","Tutor")">
                        Gia sư
                    </a>

                </li>
                <li class="nav-item p-2">
                    <a class="nav-link link text-white " href="@Url.Action("contact","Home")">
                        Liên hệ
                    </a>
                </li>
                @if (Session["UserID"] == null)
                {
                    <li class="nav-item p-2">
                        <a href="@Url.Action("register","User")" class="btn register">Đăng kí</a>
                    </li>
                    <li class="nav-item p-2">
                        <a href="@Url.Action("login","User")" class="btn login ">Đăng nhập</a>
                    </li>
                }
                else
                {

                    <li class="nav-item dropdown" style="margin-right:50px;">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Session["FullName"]
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-item p-2" href="#">Thông tin cá nhân</a>

                            <div class="dropdown-divider"></div>
                            <a class="nav-item p-2" href="/User/Logout/@Session["UserID"]">Đăng xuất</a>
                        </div>
                    </li>


                }
                <li class="nav-item p-2">

                </li>
            </ul>
        </div>
    </nav>
</header>